service: Trainning-S3

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  file:
    handler: handler.file
    events:
      - s3:
          bucket: trainningfile
          event: s3:ObjectCreated:*
  getFile:
    handler: handler.getFile
   
